base_path: "/home/fmeyer/code/repos/weather_project"
secrets: "${base_path}/secrets/api.yaml"
open_weather_api:
    current_weather: "https://api.openweathermap.org/data/2.5/weather?q="
    locations: [
        Berlin, 
        Munich,
        Cologne,
        Frankfurt,
        Bonn,
        Barcelona,
        Rome,
        ]
    unit: metric
data_storage_location: 
    landing: "${base_path}/src/landing/data"
    silver: "${base_path}/src/silver/data"
