open_weather_api:
    current_weather: "https://api.openweathermap.org/data/2.5/weather?q="
    locations: [
        Berlin, 
        Munich,
        Cologne,
        Frankfurt,
        Bonn,
        Barcelona,
        Rome,
        ]
    unit: metric
data_storage_location: 
    bronze: "/Users/fredo/Dev/Repos/weather-project/src/bronze/data"
    silver: "/Users/fredo/Dev/Repos/weather-project/src/silver/data"
      